# Question 1
Prepare the data for modelling, This will include
- Converting to lowercase
- Removing stopwords
- Lemmatization
- Stemming
- Removing numbers 

# Question 2
Once the data has been cleaned :-
- Divide the data intro train and test parts
- Convert the training and text text into vectors 
- Convert the labels intro numbers(encoding)

Overall, you should end up with 4 varaibles 
- Xtrain
- Xtest
- Ytrain
- Ytest

You can name these whatever you want, upto you. But i am looking for these 4 variables ready to go for modelling

------------

![](https://media.tenor.com/d8fG2J6pkAUAAAAC/friends-chandler.gif)

# Note 
The file is stored as a ```tsv```.

You can load a ```tsv``` file with ```pd.read_csv``` while passing the seperator or ```sep``` argument as ```\t```.

This tells pandas that the file is seperated by tab's instead of comma's

In [1]:
import pandas as pd
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
stop_words = stopwords.words("english")
from nltk.stem.snowball import SnowballStemmer
sn_stemmer = SnowballStemmer("english")
import re
import nltk
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [2]:
df = pd.read_csv('Restaurant_Reviews.tsv',sep='\t')

In [3]:
df

Review  Liked
0                             Wow... Loved this place.      1
1                                   Crust is not good.      0
2            Not tasty and the texture was just nasty.      0
3    Stopped by during the late May bank holiday of...      1
4    The selection on the menu was great and so wer...      1
..                                                 ...    ...
995  I think food should have flavor and texture an...      0
996                           Appetite instantly gone.      0
997  Overall I was not impressed and would not go b...      0
998  The whole experience was underwhelming, and I ...      0
999  Then, as if I hadn't wasted enough of my life ...      0

[1000 rows x 2 columns]

In [4]:
def new_function(x):
    x = x.lower()
    y=nltk.word_tokenize(x)
    temp=[]
    for i in y:
        if i in stopwords.words("english"): 
             pass
        else:
             temp.append(i)
    stop=' '.join(temp)
    
    c=nltk.word_tokenize(stop)
    temp2=[]
    for i in c:
        temp2.append(lemmatizer.lemmatize(i))
        lem=' '.join(temp2)
        
    d=nltk.word_tokenize(lem)
    temp3 = []
    for i in d:
        temp3.append((sn_stemmer.stem(i)))
        stem=' '.join(temp3)

    temp4 = []
    for i in stem:
        if i.isdigit():
            pass
        else:
            temp4.append(i)
        number =''.join(temp4)
    return(number)

In [14]:
df['Clean Msg'] = df['Review'].apply(new_function)

In [15]:
df

Review  Liked  \
0                             Wow... Loved this place.      1   
1                                   Crust is not good.      0   
2            Not tasty and the texture was just nasty.      0   
3    Stopped by during the late May bank holiday of...      1   
4    The selection on the menu was great and so wer...      1   
..                                                 ...    ...   
995  I think food should have flavor and texture an...      0   
996                           Appetite instantly gone.      0   
997  Overall I was not impressed and would not go b...      0   
998  The whole experience was underwhelming, and I ...      0   
999  Then, as if I hadn't wasted enough of my life ...      0   

                                            Clean Msg   \
0                                 wow ... love place .   
1                                         crust good .   
2                                 tasti textur nasti .   
3    stop late may bank holiday rick steve recommen...   
4                            select menu great price .   
..                                                 ...   
995                    think food flavor textur lack .   
996                             appetit instant gone .   
997                     overal impress would go back .   
998  whole experi underwhelm , think ll go ninja su...   
999  , n't wast enough life , pour salt wound draw ...   

                                             Clean Msg  
0                                 wow ... love place .  
1                                         crust good .  
2                                 tasti textur nasti .  
3    stop late may bank holiday rick steve recommen...  
4                            select menu great price .  
..                                                 ...  
995                    think food flavor textur lack .  
996                             appetit instant gone .  
997                     overal impress would go back .  
998  whole experi underwhelm , think ll go ninja su...  
999  , n't wast enough life , pour salt wound draw ...  

[1000 rows x 4 columns]

In [16]:
df_x = df['Clean Msg']

In [17]:
df_y = df['Liked']

In [18]:
X_train, X_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.33, random_state=42)

In [19]:
train_test_split(df_x, df_y, test_size=0.2)

[90               summari , larg disappoint dine experi .
 675                       fantast neighborhood gem ! ! !
 130                      place way overpr mediocr food .
 329            mom got home immedi got sick bite salad .
 426      serious good pizza 'm expert/connisseur topic .
                              ...                        
 607                                          want leav .
 623    drive thru mean want wait around half hour foo...
 535              excel new restaur experienc frenchman .
 99                   side , cafe serf realli good food .
 549    boyfriend came first time recent trip vega cou...
 Name: Clean Msg, Length: 800, dtype: object,
 273    stop place madison ironman , friend , kind sta...
 841                                food came good pace .
 198                                       friend staff .
 603              good valu , great food , great servic .
 661                            conveni , sinc stay mgm !
                          

In [20]:
X_train

703                      server nice attent serv staff .
311            order toast english muffin came untoast .
722                 food great alway , compliment chef .
629    staff alway super friend help , especi cool br...
0                                   wow ... love place .
                             ...                        
106    food delici , bartend attent person got great ...
270                          veggitarian platter world !
860        place pretti good , nice littl vibe restaur .
435          huge awkward .lb piec cow /ths gristl fat .
102                      best buffet town , price beat .
Name: Clean Msg, Length: 670, dtype: object

In [21]:
X_test

521                                        n't gone go !
737    tri airport experi tasti food speedi , friend ...
740                  restaur clean famili restaur feel .
660    person love hummus , pita , baklava , falafel ...
411                      come hungri , leav happi stuf !
                             ...                        
506                            overal n't impress noca .
342            veget fresh sauc feel like authent thai .
485     n't small famili restaur , fine dine establish .
711                                              thing .
133                                         manag rude .
Name: Clean Msg, Length: 330, dtype: object

In [22]:
y_train

703    1
311    0
722    1
629    1
0      1
      ..
106    1
270    1
860    1
435    0
102    1
Name: Liked, Length: 670, dtype: int64

In [23]:
y_test

521    1
737    1
740    1
660    1
411    1
      ..
506    0
342    1
485    1
711    0
133    0
Name: Liked, Length: 330, dtype: int64

In [24]:
countvector = CountVectorizer()
countvector.fit(X_train)

CountVectorizer()

In [25]:
countvector.transform(X_train)

<670x1255 sparse matrix of type '<class 'numpy.int64'>'
	with 3693 stored elements in Compressed Sparse Row format>

In [26]:
countvector.get_feature_names_out()[100:200]

array(['bill', 'bird', 'biscuit', 'bisqu', 'bit', 'bitch', 'bite',
       'black', 'blah', 'blame', 'bland', 'blanket', 'bloodi', 'blown',
       'blue', 'boba', 'bode', 'bone', 'book', 'boot', 'bore', 'bother',
       'bottom', 'bouchon', 'bought', 'bowl', 'boy', 'boyfriend', 'bread',
       'break', 'breakfast', 'breez', 'brick', 'bring', 'brother',
       'brought', 'brownish', 'brunch', 'bruschetta', 'buck', 'buffet',
       'build', 'buldogi', 'bunch', 'burger', 'burritto', 'bus', 'busi',
       'bussel', 'butter', 'bye', 'ca', 'caballero', 'caesar', 'cafe',
       'café', 'calamari', 'call', 'calligraphi', 'came', 'camelback',
       'cant', 'cape', 'caper', 'car', 'care', 'cart', 'cartel', 'case',
       'cash', 'cashew', 'cashier', 'casino', 'caterpillar', 'caught',
       'caus', 'certain', 'chai', 'chain', 'chang', 'char', 'charcoal',
       'charm', 'cheap', 'check', 'cheek', 'chees', 'cheeseburg',
       'cheesecurd', 'chef', 'chewi', 'chicken', 'chines', 'chip',
       'ch

In [27]:
x_train_vec = countvector.transform(X_train)

In [28]:
x_train_vec

<670x1255 sparse matrix of type '<class 'numpy.int64'>'
	with 3693 stored elements in Compressed Sparse Row format>

In [29]:
countvector.transform(X_test)

<330x1255 sparse matrix of type '<class 'numpy.int64'>'
	with 1390 stored elements in Compressed Sparse Row format>

In [30]:
x_test_vec = countvector.transform(X_test)

In [31]:
le.fit(y_train)

LabelEncoder()

In [32]:
le.classes_

array([0, 1], dtype=int64)

In [33]:
le.transform(y_train)

array([1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0,

In [34]:
le.transform(y_test)

array([1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,

In [35]:
y_train_encoded = le.transform(y_train)

In [36]:
y_test_encoded = le.transform(y_test)

# Now we have 4 variables ready to go for modelling
- x_train_vec
- x_test_vec
- y_train_encoded
- y_test_encoded